version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ServicesApi
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USER: root
    volumes:
      #- ./mysql-data:/var/lib/mysql
      - ./sql-import:/var/www
    ports:
      - '3306:3306'
  php-apache:
    container_name: php-apache
    build:
      context: ./php-apache/
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database